from django.contrib import admin
from Modulos.Productos.models import *

# Register your models here.

admin.site.register(Categoria)
admin.site.register(Fabricante)
admin.site.register(Presentacion)
admin.site.register(Pais)
admin.site.register(Unidad_Medida)
admin.site.register(Via_Administracion)
admin.site.register(Tipo_Prescripcion)
admin.site.register(Componente)
admin.site.register(Impuesto)
admin.site.register(Indicacion)
admin.site.register(Producto)
admin.site.register(Producto_Componente)
admin.site.register(Producto_Impuesto)
admin.site.register(Producto_Indicacion)
admin.site.register(Sucursal)
admin.site.register(Inventario)
admin.site.register(Tipo_Cliente)
admin.site.register(Genero)
admin.site.register(Cliente)
admin.site.register(Forma_Pago)
admin.site.register(Proveedor)
admin.site.register(Venta)
admin.site.register(Detalle_Venta)
admin.site.register(Compra)
admin.site.register(Detalle_Compra)
admin.site.register(Tipo_Mov)
admin.site.register(Mov_Inventario)
admin.site.register(Envio_Salida)
admin.site.register(Detalle_Envio_Salida)
admin.site.register(Envio_Entrada)
admin.site.register(Detalle_Envio_Entrada)
admin.site.register(Producto_Proveedor)
