# Generated by Django 3.2.11 on 2022-07-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_auto_20220622_0647'),
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sucursales',
            field=models.ManyToManyField(to='Productos.Sucursal'),
        ),
    ]
