# Generated by Django 3.2.11 on 2022-03-05 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ingrese la descripción de la categoría', max_length=30)),
                ('abreviatura', models.CharField(help_text='Ingrese la abreviatura a utilizar', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ingrese la descripción descripción del ingrediente activo', max_length=100)),
                ('abreviatura', models.CharField(help_text='Ingrese la abreviatura a utilizar', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id_fabricante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingrese el nombre del fabricante', max_length=100)),
                ('abreviatura', models.CharField(help_text='Ingrese la abreviatura a utilizar', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id_impuesto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ingrese la descripción del impuesto', max_length=30)),
                ('porcentaje', models.DecimalField(decimal_places=3, help_text='Ingrese la abreviatura a utilizar', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Indicacion',
            fields=[
                ('id_indicacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ingrese la descripción de la indicación', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingrese el nombre del país', max_length=100)),
                ('abreviatura', models.CharField(help_text='Ingrese la abreviatura a utilizar', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id_presentacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ingrese la descripción de la presentación (tabletas, jarabe, etc.)', max_length=30)),
                ('abreviatura', models.CharField(help_text='Ingrese la abreviatura a utilizar', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_barras_1', models.CharField(help_text='Ingrese el código de barras', max_length=13)),
                ('codigo_barras_2', models.CharField(help_text='Ingrese el código de barras secundario', max_length=13)),
                ('nombre_compra', models.CharField(help_text='Ingrese el nombre para efectos de compras', max_length=60)),
                ('nombre_venta', models.CharField(help_text='Ingrese el nombre para efectos de ventas', max_length=60)),
                ('nombre_corto', models.CharField(help_text='Ingrese el nombre corto para facturación', max_length=15)),
                ('conversion', models.PositiveIntegerField(default=1, help_text='Ingrese la conversión del producto en sucursales')),
                ('prioridad', models.PositiveIntegerField(default=3, help_text='Ingrese la prioridad del producto')),
                ('imagen', models.ImageField(help_text='Seleccione la imagen del producto', upload_to='media/images')),
                ('afecto_impuesto', models.BooleanField(default=False, help_text='Marque si el producto es afecto a impuestos')),
                ('registro_sanitario', models.CharField(help_text='Ingrese el registro sanitario del producto', max_length=20)),
                ('precio_costo', models.DecimalField(decimal_places=5, help_text='Ingrese el precio costo del producto', max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Ingrese el precio de venta del producto', max_digits=7)),
                ('clasificacion_abc', models.CharField(default='C', help_text='Ingrese la clasificación ABC a la que pertenece el producto', max_length=1)),
                ('id_categoria', models.ForeignKey(help_text='Seleccione la categoría a la que pertenece', on_delete=django.db.models.deletion.CASCADE, to='Productos.categoria')),
                ('id_fabricante', models.ForeignKey(help_text='Seleccione el fabricante del producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.fabricante')),
                ('id_pais', models.ForeignKey(help_text='Seleccione el país de origen del producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.pais')),
                ('id_presentacion', models.ForeignKey(help_text='Seleccione la presentación del producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.presentacion')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Prescripcion',
            fields=[
                ('id_tipo_prescripcion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ingrese la descripción del tipo de prescripción', max_length=30)),
                ('abreviatura', models.CharField(help_text='Ingrese la abreviatura a utilizar', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_Medida',
            fields=[
                ('id_unidad_medida', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ingrese la descripción de la unidad de medida (caja, frasco, botella, etc.)', max_length=30)),
                ('abreviatura', models.CharField(help_text='Ingrese la abreviatura a utilizar', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Via_Administracion',
            fields=[
                ('id_via_administracion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ingrese la descripción de la vía de administración (oral, tópica, vaginal, etc.)', max_length=30)),
                ('abreviatura', models.CharField(help_text='Ingrese la abreviatura a utilizar', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Indicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(help_text='Ingrese la dosis del producto', max_length=20)),
                ('id_indicacion', models.ForeignKey(help_text='Seleccione la indicación para la que sirve el producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.indicacion')),
                ('id_producto', models.ForeignKey(help_text='Seleccione el producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=3, help_text='Ingrese el porcentaje de impuesto', max_digits=5)),
                ('id_impuesto', models.ForeignKey(help_text='Seleccione el impuesto al que está afecto el producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.impuesto')),
                ('id_producto', models.ForeignKey(help_text='Seleccione el producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(help_text='Ingrese la cantidad de ingrediente activo en el producto', max_length=20)),
                ('id_componente', models.ForeignKey(help_text='Seleccione el ingrediente activo del producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.componente')),
                ('id_producto', models.ForeignKey(help_text='Seleccione el producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_tipo_prescripcion',
            field=models.ForeignKey(help_text='Seleccione las prescripciones del producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.tipo_prescripcion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_unidad_medida',
            field=models.ForeignKey(help_text='Seleccione la unidad de medida del proeducto', on_delete=django.db.models.deletion.CASCADE, to='Productos.unidad_medida'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_via_administracion',
            field=models.ForeignKey(help_text='Ingrese ', on_delete=django.db.models.deletion.CASCADE, to='Productos.via_administracion'),
        ),
    ]
