# Generated by Django 3.2.11 on 2022-06-06 06:23

import Modulos.Productos.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', Modulos.Productos.models.UpperField(help_text='Ingrese la descripción de la categoría', max_length=30, unique=True)),
                ('abreviatura', Modulos.Productos.models.UpperField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', Modulos.Productos.models.UpperField(max_length=150, verbose_name='Nombre')),
                ('nit', Modulos.Productos.models.UpperField(max_length=10, verbose_name='Nit')),
                ('telefono', Modulos.Productos.models.UpperField(max_length=10, verbose_name='Teléfono')),
                ('direccion', Modulos.Productos.models.UpperField(max_length=150, verbose_name='Dirección')),
                ('nacimiento', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', Modulos.Productos.models.UpperField(help_text='Ingrese la descripción descripción del ingrediente activo', max_length=150, unique=True)),
                ('abreviatura', Modulos.Productos.models.UpperField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=15, null=True)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id_fabricante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', Modulos.Productos.models.UpperField(help_text='Ingrese el nombre del fabricante', max_length=100, unique=True)),
                ('abreviatura', Modulos.Productos.models.UpperField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Forma_Pago',
            fields=[
                ('id_forma_pago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', Modulos.Productos.models.UpperField(help_text='Ingrese la descripción de la forma de pago', max_length=30, unique=True)),
                ('abreviatura', Modulos.Productos.models.UpperField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', Modulos.Productos.models.UpperField(max_length=50, unique=True, verbose_name='Descripción')),
                ('abreviatura', Modulos.Productos.models.UpperField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id_impuesto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', Modulos.Productos.models.UpperField(help_text='Ingrese la descripción del impuesto', max_length=30, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=3, help_text='Ingrese la abreviatura a utilizar', max_digits=5)),
                ('abreviatura', Modulos.Productos.models.UpperField(default='', help_text='Ingrese la abreviatura a utilizar', max_length=10)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Indicacion',
            fields=[
                ('id_indicacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', Modulos.Productos.models.UpperField(help_text='Ingrese la descripción de la indicación', max_length=100, unique=True)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', Modulos.Productos.models.UpperField(help_text='Ingrese el nombre del país', max_length=100, unique=True)),
                ('abreviatura', Modulos.Productos.models.UpperField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id_presentacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', Modulos.Productos.models.UpperField(help_text='Ingrese la descripción de la presentación (tabletas, jarabe, etc.)', max_length=100, unique=True)),
                ('abreviatura', Modulos.Productos.models.UpperField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_barras_1', models.CharField(help_text='Ingrese el código de barras', max_length=13)),
                ('codigo_barras_2', models.CharField(help_text='Ingrese el código de barras secundario', max_length=13)),
                ('nombre_compra', Modulos.Productos.models.UpperField(help_text='Ingrese el nombre para efectos de compras', max_length=60, unique=True)),
                ('nombre_venta', Modulos.Productos.models.UpperField(help_text='Ingrese el nombre para efectos de ventas', max_length=60, unique=True)),
                ('nombre_corto', Modulos.Productos.models.UpperField(help_text='Ingrese el nombre corto para facturación', max_length=15, unique=True)),
                ('conversion', models.PositiveIntegerField(default=1, help_text='Ingrese la conversión del producto en sucursales')),
                ('prioridad', models.PositiveIntegerField(default=3, help_text='Ingrese la prioridad del producto')),
                ('imagen', models.ImageField(blank=True, help_text='Seleccione la imagen del producto', null=True, upload_to='product/%Y/%m/%d')),
                ('afecto_impuesto', models.BooleanField(default=False, help_text='Marque si el producto es afecto a impuestos')),
                ('registro_sanitario', models.CharField(help_text='Ingrese el registro sanitario del producto', max_length=20)),
                ('precio_costo', models.DecimalField(decimal_places=5, help_text='Ingrese el precio costo del producto', max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Ingrese el precio de venta del producto', max_digits=7)),
                ('clasificacion_abc', models.CharField(default='C', help_text='Ingrese la clasificación ABC a la que pertenece el producto', max_length=1)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('id_categoria', models.ForeignKey(help_text='Seleccione la categoría a la que pertenece', on_delete=django.db.models.deletion.CASCADE, to='Productos.categoria')),
                ('id_fabricante', models.ForeignKey(help_text='Seleccione el fabricante del producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.fabricante')),
                ('id_pais', models.ForeignKey(help_text='Seleccione el país de origen del producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.pais')),
                ('id_presentacion', models.ForeignKey(help_text='Seleccione la presentación del producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.presentacion')),
            ],
            options={
                'ordering': ['nombre_venta'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', Modulos.Productos.models.UpperField(max_length=150, unique=True, verbose_name='Nombre')),
                ('nit', Modulos.Productos.models.UpperField(max_length=150, verbose_name='Nit')),
                ('direccion', Modulos.Productos.models.UpperField(max_length=150, verbose_name='Dirección')),
                ('telefono', Modulos.Productos.models.UpperField(max_length=150, verbose_name='Teléfono')),
                ('contacto', Modulos.Productos.models.UpperField(max_length=150, verbose_name='Contacto')),
                ('correo', Modulos.Productos.models.UpperField(max_length=150, verbose_name='Correo')),
                ('limite_credito', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Límite de Crédito')),
                ('periodo_credito', models.PositiveIntegerField(default=0, verbose_name='Período de Crédito')),
                ('estado', models.CharField(default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', Modulos.Productos.models.UpperField(help_text='Ingrese la descripción de la sucursal', max_length=30, unique=True)),
                ('direccion', Modulos.Productos.models.UpperField(help_text='Ingrese la dirección de la sucursal', max_length=100)),
                ('telefono', Modulos.Productos.models.UpperField(help_text='Ingrese el teléfono de la sucursal', max_length=30)),
                ('abreviatura', Modulos.Productos.models.UpperField(help_text='Ingrese la abreviatura a utilizar', max_length=8)),
                ('encargado', Modulos.Productos.models.UpperField(help_text='Ingrese el nombre del encargado de la sucursal', max_length=100)),
                ('email', models.EmailField(help_text='Ingrese el correo del encargado de la sucursal', max_length=100)),
                ('tipo', models.CharField(help_text='C = Centro de Distribución, S = Sucursal', max_length=1)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Cliente',
            fields=[
                ('id_tipo_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', Modulos.Productos.models.UpperField(max_length=25, unique=True, verbose_name='Descripción')),
                ('abreviatura', Modulos.Productos.models.UpperField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Prescripcion',
            fields=[
                ('id_tipo_prescripcion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', Modulos.Productos.models.UpperField(help_text='Ingrese la descripción del tipo de prescripción', max_length=30, unique=True)),
                ('abreviatura', Modulos.Productos.models.UpperField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Unidad_Medida',
            fields=[
                ('id_unidad_medida', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', Modulos.Productos.models.UpperField(help_text='Ingrese la descripción de la unidad de medida (caja, frasco, botella, etc.)', max_length=30, unique=True)),
                ('abreviatura', Modulos.Productos.models.UpperField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Via_Administracion',
            fields=[
                ('id_via_administracion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', Modulos.Productos.models.UpperField(help_text='Ingrese la descripción de la vía de administración (oral, tópica, vaginal, etc.)', max_length=100, unique=True)),
                ('abreviatura', Modulos.Productos.models.UpperField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('nombre', Modulos.Productos.models.UpperField(max_length=150)),
                ('nit', Modulos.Productos.models.UpperField(max_length=10)),
                ('telefono', Modulos.Productos.models.UpperField(max_length=10)),
                ('direccion', Modulos.Productos.models.UpperField(max_length=150)),
                ('subtotal_afecto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('subtotal_noafecto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('vendedor', models.PositiveIntegerField(default=1)),
                ('cajero', models.PositiveIntegerField(default=1)),
                ('correlativo_diario', models.PositiveIntegerField(default=1)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.cliente')),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.sucursal')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id_venta'],
            },
        ),
        migrations.CreateModel(
            name='Producto_Indicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', Modulos.Productos.models.UpperField(help_text='Ingrese la dosis del producto', max_length=20)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('id_indicacion', models.ForeignKey(help_text='Seleccione la indicación para la que sirve el producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.indicacion')),
                ('id_producto', models.ForeignKey(help_text='Seleccione el producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=3, help_text='Ingrese el porcentaje de impuesto', max_digits=5)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('id_impuesto', models.ForeignKey(help_text='Seleccione el impuesto al que está afecto el producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.impuesto')),
                ('id_producto', models.ForeignKey(help_text='Seleccione el producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', Modulos.Productos.models.UpperField(help_text='Ingrese la cantidad de ingrediente activo en el producto', max_length=20)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('id_componente', models.ForeignKey(help_text='Seleccione el ingrediente activo del producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.componente')),
                ('id_producto', models.ForeignKey(help_text='Seleccione el producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_tipo_prescripcion',
            field=models.ForeignKey(help_text='Seleccione las prescripciones del producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.tipo_prescripcion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_unidad_medida',
            field=models.ForeignKey(help_text='Seleccione la unidad de medida del proeducto', on_delete=django.db.models.deletion.CASCADE, to='Productos.unidad_medida'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_via_administracion',
            field=models.ForeignKey(help_text='Ingrese ', on_delete=django.db.models.deletion.CASCADE, to='Productos.via_administracion'),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.BigAutoField(primary_key=True, serialize=False)),
                ('existencia', models.IntegerField(default=0)),
                ('ubicacion', Modulos.Productos.models.UpperField(help_text='Ingrese la ubicación del producto en la sucursal', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('id_producto', models.ForeignKey(help_text='Seleccione el producto al que pertenece', on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
                ('id_sucursal', models.ForeignKey(help_text='Seleccione la sucursal a la que pertenece', on_delete=django.db.models.deletion.CASCADE, to='Productos.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id_detalle_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('precio_costo', models.DecimalField(decimal_places=5, max_digits=9)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=7)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.venta')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.ForeignKey(help_text='Seleccione el género del cliente', on_delete=django.db.models.deletion.CASCADE, to='Productos.genero'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_tipo_cliente',
            field=models.ForeignKey(default=1, help_text='Seleccione el tipo de cliente', on_delete=django.db.models.deletion.CASCADE, to='Productos.tipo_cliente'),
        ),
    ]
