# Generated by Django 3.2.11 on 2022-04-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='estado',
            field=models.CharField(default='A', help_text='Ingrese el estado', max_length=1),
        ),
    ]
