# Generated by Django 3.2.11 on 2022-03-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.CharField(default='A', help_text='Ingrese el estado', max_length=1),
        ),
        migrations.AddField(
            model_name='componente',
            name='estado',
            field=models.CharField(default='A', help_text='Ingrese el estado', max_length=1),
        ),
        migrations.AddField(
            model_name='fabricante',
            name='estado',
            field=models.CharField(default='A', help_text='Ingrese el estado', max_length=1),
        ),
        migrations.AddField(
            model_name='impuesto',
            name='estado',
            field=models.CharField(default='A', help_text='Ingrese el estado', max_length=1),
        ),
        migrations.AddField(
            model_name='indicacion',
            name='estado',
            field=models.CharField(default='A', help_text='Ingrese el estado', max_length=1),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='estado',
            field=models.CharField(default='A', help_text='Ingrese el estado', max_length=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(default='A', help_text='Ingrese el estado', max_length=1),
        ),
        migrations.AddField(
            model_name='producto_componente',
            name='estado',
            field=models.CharField(default='A', help_text='Ingrese el estado', max_length=1),
        ),
        migrations.AddField(
            model_name='producto_impuesto',
            name='estado',
            field=models.CharField(default='A', help_text='Ingrese el estado', max_length=1),
        ),
        migrations.AddField(
            model_name='producto_indicacion',
            name='estado',
            field=models.CharField(default='A', help_text='Ingrese el estado', max_length=1),
        ),
        migrations.AddField(
            model_name='tipo_prescripcion',
            name='estado',
            field=models.CharField(default='A', help_text='Ingrese el estado', max_length=1),
        ),
        migrations.AddField(
            model_name='unidad_medida',
            name='estado',
            field=models.CharField(default='A', help_text='Ingrese el estado', max_length=1),
        ),
        migrations.AddField(
            model_name='via_administracion',
            name='estado',
            field=models.CharField(default='A', help_text='Ingrese el estado', max_length=1),
        ),
    ]
