# Generated by Django 3.2.11 on 2022-04-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_pais_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Seleccione la imagen del producto', null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='via_administracion',
            name='descripcion',
            field=models.CharField(help_text='Ingrese la descripción de la vía de administración (oral, tópica, vaginal, etc.)', max_length=100, unique=True),
        ),
    ]
