# Generated by Django 3.2.11 on 2022-03-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_auto_20220306_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='descripcion',
            field=models.CharField(help_text='Ingrese la descripción de la presentación (tabletas, jarabe, etc.)', max_length=100),
        ),
    ]
