# Generated by Django 3.2.11 on 2022-04-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_auto_20220427_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Seleccione la imagen del producto', null=True, upload_to='product/%Y/%m/%d'),
        ),
    ]
