# Generated by Django 3.2.11 on 2022-03-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_alter_presentacion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='via_administracion',
            name='descripcion',
            field=models.CharField(help_text='Ingrese la descripción de la vía de administración (oral, tópica, vaginal, etc.)', max_length=100),
        ),
    ]
