# Generated by Django 3.2.11 on 2022-07-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_alter_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='principios_activos',
            field=models.ManyToManyField(to='Productos.Componente'),
        ),
    ]
