# Generated by Django 3.2.11 on 2022-03-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_alter_via_administracion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='descripcion',
            field=models.CharField(help_text='Ingrese la descripción descripción del ingrediente activo', max_length=150),
        ),
    ]
