# Generated by Django 3.2.11 on 2022-07-14 23:53

import Modulos.Productos.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_producto_principios_activos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('serie', Modulos.Productos.models.UpperField(max_length=15)),
                ('numero', Modulos.Productos.models.UpperField(max_length=15)),
                ('face', Modulos.Productos.models.UpperField(max_length=50, unique=True)),
                ('subtotal_afecto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('subtotal_noafecto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('usuario', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.cliente')),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.sucursal')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['id_compra'],
            },
        ),
        migrations.CreateModel(
            name='Envio_Entrada',
            fields=[
                ('id_envio_entrada', models.BigAutoField(primary_key=True, serialize=False)),
                ('origen', models.IntegerField()),
                ('destino', models.IntegerField()),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('notas', Modulos.Productos.models.UpperField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('usuario', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Envio_Salida',
            fields=[
                ('id_envio_salida', models.BigAutoField(primary_key=True, serialize=False)),
                ('origen', models.IntegerField()),
                ('destino', models.IntegerField()),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('notas', Modulos.Productos.models.UpperField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('usuario', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField()),
                ('id_proveedor', models.IntegerField()),
                ('cod_producto_proveedor', Modulos.Productos.models.UpperField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Mov',
            fields=[
                ('id_tipo_mov', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', Modulos.Productos.models.UpperField(max_length=30, unique=True)),
                ('abreviatura', Modulos.Productos.models.UpperField(blank=True, max_length=5, null=True)),
                ('signo', models.CharField(default='+', max_length=1)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='email',
            field=models.EmailField(default='sc@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='venta',
            name='se_factura',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Mov_Inventario',
            fields=[
                ('id_mov_inventario', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_mov', models.BigIntegerField()),
                ('signo', models.CharField(max_length=1)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.sucursal')),
                ('id_tipo_mov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.tipo_mov')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Envio_Salida',
            fields=[
                ('id_detalle_envio_salida', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('precio_venta', models.DecimalField(decimal_places=5, max_digits=9)),
                ('id_envio_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.compra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Envio_Entrada',
            fields=[
                ('id_detalle_envio_entrada', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('precio_venta', models.DecimalField(decimal_places=5, max_digits=9)),
                ('id_envio_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.compra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Compra',
            fields=[
                ('id_detalle_compra', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('precio_costo', models.DecimalField(decimal_places=5, max_digits=9)),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.compra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
        ),
    ]
