# Generated by Django 3.2.11 on 2022-05-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='abreviatura',
            field=models.CharField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='componente',
            name='abreviatura',
            field=models.CharField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fabricante',
            name='abreviatura',
            field=models.CharField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='abreviatura',
            field=models.CharField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='abreviatura',
            field=models.CharField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_prescripcion',
            name='abreviatura',
            field=models.CharField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='unidad_medida',
            name='abreviatura',
            field=models.CharField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='via_administracion',
            name='abreviatura',
            field=models.CharField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True),
        ),
    ]
