# Generated by Django 3.2.11 on 2022-05-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_auto_20220506_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(help_text='Ingrese la descripción de la categoría', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='componente',
            name='descripcion',
            field=models.CharField(help_text='Ingrese la descripción descripción del ingrediente activo', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='fabricante',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre del fabricante', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='descripcion',
            field=models.CharField(help_text='Ingrese la descripción del impuesto', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='indicacion',
            name='descripcion',
            field=models.CharField(help_text='Ingrese la descripción de la indicación', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre del país', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='descripcion',
            field=models.CharField(help_text='Ingrese la descripción de la presentación (tabletas, jarabe, etc.)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_compra',
            field=models.CharField(help_text='Ingrese el nombre para efectos de compras', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_corto',
            field=models.CharField(help_text='Ingrese el nombre corto para facturación', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_venta',
            field=models.CharField(help_text='Ingrese el nombre para efectos de ventas', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_prescripcion',
            name='descripcion',
            field=models.CharField(help_text='Ingrese la descripción del tipo de prescripción', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='unidad_medida',
            name='descripcion',
            field=models.CharField(help_text='Ingrese la descripción de la unidad de medida (caja, frasco, botella, etc.)', max_length=30, unique=True),
        ),
    ]
