# Generated by Django 3.2.11 on 2022-03-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_alter_componente_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='abreviatura',
            field=models.CharField(help_text='Ingrese la abreviatura a utilizar', max_length=15),
        ),
    ]
