# Generated by Django 3.2.11 on 2022-03-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_alter_componente_abreviatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='impuesto',
            name='abreviatura',
            field=models.CharField(default='', help_text='Ingrese la abreviatura a utilizar', max_length=10),
        ),
    ]
