# Generated by Django 3.2.11 on 2022-05-06 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_auto_20220506_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ingrese la descripción de la sucursal', max_length=30, unique=True)),
                ('direccion', models.CharField(help_text='Ingrese la dirección de la sucursal', max_length=100)),
                ('telefono', models.CharField(help_text='Ingrese el teléfono de la sucursal', max_length=30)),
                ('abreviatura', models.CharField(help_text='Ingrese la abreviatura a utilizar', max_length=8)),
                ('encargado', models.CharField(help_text='Ingrese el nombre del encargado de la sucursal', max_length=100)),
                ('email', models.EmailField(help_text='Ingrese el correo del encargado de la sucursal', max_length=100)),
                ('tipo', models.CharField(help_text='C = Centro de Distribución, S = Sucursal', max_length=1)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.BigAutoField(primary_key=True, serialize=False)),
                ('existencia', models.IntegerField(default=0)),
                ('ubicacion', models.CharField(help_text='Ingrese la ubicación del producto en la sucursal', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('id_producto', models.ForeignKey(help_text='Seleccione el producto al que pertenece', on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
                ('id_sucursal', models.ForeignKey(help_text='Seleccione la sucursal a la que pertenece', on_delete=django.db.models.deletion.CASCADE, to='Productos.sucursal')),
            ],
        ),
    ]
