# Generated by Django 3.2.11 on 2022-03-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_impuesto_abreviatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['descripcion']},
        ),
        migrations.AlterModelOptions(
            name='componente',
            options={'ordering': ['descripcion']},
        ),
        migrations.AlterModelOptions(
            name='fabricante',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='impuesto',
            options={'ordering': ['descripcion']},
        ),
        migrations.AlterModelOptions(
            name='indicacion',
            options={'ordering': ['descripcion']},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='presentacion',
            options={'ordering': ['descripcion']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre_venta']},
        ),
        migrations.AlterModelOptions(
            name='tipo_prescripcion',
            options={'ordering': ['descripcion']},
        ),
        migrations.AlterModelOptions(
            name='unidad_medida',
            options={'ordering': ['descripcion']},
        ),
        migrations.AlterModelOptions(
            name='via_administracion',
            options={'ordering': ['descripcion']},
        ),
    ]
