# Generated by Django 3.2.11 on 2022-05-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_inventario_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='tipo',
            field=models.CharField(blank=True, help_text='C = Centro de Distribución, S = Sucursal', max_length=1, null=True),
        ),
    ]
