# Generated by Django 3.2.11 on 2022-07-23 00:20

import Modulos.Productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_alter_compra_id_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nit', Modulos.Productos.models.UpperField(max_length=30, unique=True)),
                ('nombre', Modulos.Productos.models.UpperField(max_length=100, unique=True)),
                ('razon', Modulos.Productos.models.UpperField(max_length=100, unique=True)),
                ('direccion', Modulos.Productos.models.UpperField(max_length=100, unique=True)),
                ('telefono', Modulos.Productos.models.UpperField(max_length=30, unique=True)),
                ('email', Modulos.Productos.models.UpperField(max_length=100, unique=True)),
                ('web', Modulos.Productos.models.UpperField(max_length=100, unique=True)),
                ('contacto', Modulos.Productos.models.UpperField(max_length=100, unique=True)),
            ],
        ),
    ]
