# Generated by Django 3.2.11 on 2022-05-12 23:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0010_auto_20220511_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma_Pago',
            fields=[
                ('id_forma_pago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ingrese la descripción de la forma de pago', max_length=30, unique=True)),
                ('abreviatura', models.CharField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True)),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('nit', models.CharField(max_length=150, verbose_name='Nit')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=150, verbose_name='Teléfono')),
                ('contacto', models.CharField(max_length=150, verbose_name='Contacto')),
                ('correo', models.CharField(max_length=150, verbose_name='Correo')),
                ('limite_credito', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Límite de Crédito')),
                ('periodo_credito', models.PositiveIntegerField(default=0, verbose_name='Período de Crédito')),
                ('estado', models.CharField(default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Cliente',
            fields=[
                ('id_tipo_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=25, verbose_name='Descripción')),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='user_updated',
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres')),
                ('nit', models.CharField(max_length=10, verbose_name='Nit')),
                ('telefono', models.CharField(max_length=10, verbose_name='Nit')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('nacimiento', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('estado', models.CharField(default='A', help_text='Ingrese el estado', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('genero', models.ForeignKey(help_text='Seleccione el género del cliente', on_delete=django.db.models.deletion.CASCADE, related_name='cliente_genero', to='Productos.genero')),
                ('id_tipo_prescripcion', models.ForeignKey(help_text='Seleccione el tipo de cliente', on_delete=django.db.models.deletion.CASCADE, related_name='cliente_tipo', to='Productos.tipo_cliente')),
            ],
        ),
    ]
