# Generated by Django 3.2.11 on 2022-05-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0011_auto_20220512_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_cliente',
            name='abreviatura',
            field=models.CharField(blank=True, help_text='Ingrese la abreviatura a utilizar', max_length=5, null=True),
        ),
    ]
