# Generated by Django 3.2.11 on 2022-05-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0012_tipo_cliente_abreviatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipo_cliente',
            name='descripcion',
            field=models.CharField(max_length=25, unique=True, verbose_name='Descripción'),
        ),
    ]
