# Generated by Django 3.2.11 on 2022-05-19 05:12

import Modulos.Productos.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0013_auto_20220519_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=Modulos.Productos.models.UpperField(help_text='Ingrese la descripción de la categoría', max_length=30, unique=True),
        ),
    ]
