# Generated by Django 3.2.11 on 2022-05-19 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0015_auto_20220519_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_tipo_prescripcion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_tipo_cliente',
            field=models.ForeignKey(default=1, help_text='Seleccione el tipo de cliente', on_delete=django.db.models.deletion.CASCADE, to='Productos.tipo_cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.ForeignKey(help_text='Seleccione el género del cliente', on_delete=django.db.models.deletion.CASCADE, to='Productos.genero'),
        ),
    ]
