# Generated by Django 3.2.11 on 2022-05-21 00:48

import Modulos.Productos.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0016_auto_20220519_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('nombre', Modulos.Productos.models.UpperField(max_length=150)),
                ('nit', Modulos.Productos.models.UpperField(max_length=10)),
                ('telefono', Modulos.Productos.models.UpperField(max_length=10)),
                ('direccion', Modulos.Productos.models.UpperField(max_length=150)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.cliente')),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.sucursal')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id_venta'],
            },
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id_detalle_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('id_empresa', models.PositiveIntegerField(default=1)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.venta')),
            ],
        ),
    ]
