# Generated by Django 3.2.11 on 2022-05-21 19:32

import Modulos.Productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0017_detalle_venta_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='aaaaa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', Modulos.Productos.models.UpperField(max_length=150)),
            ],
        ),
    ]
